### ISSUE TITLE
LoadError: cannot load such file -- oily_png/oily_png

### ISSUE THREAD

**Issue by sammdec** [layervault/psd.rb#28]
For some reason I have just updated my bundle and Im receiving the following error.
`LoadError: cannot load such file -- oily_png/oily_png`. 

On my other system it is all running fine, so Im not sure what could be causing the error.
Here is the stacktrace:

```
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/oily_png-1.1.0/lib/oily_png.rb:19:in `require'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/oily_png-1.1.0/lib/oily_png.rb:19:in `<top (required)>'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/psd-1.0.0/lib/psd/image_exports/png.rb:1:in `require'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/psd-1.0.0/lib/psd/image_exports/png.rb:1:in `<top (required)>'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/psd-1.0.0/lib/psd.rb:15:in `require'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/psd-1.0.0/lib/psd.rb:15:in `block (2 levels) in <top (required)>'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/psd-1.0.0/lib/psd.rb:15:in `glob'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/psd-1.0.0/lib/psd.rb:15:in `block in <top (required)>'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/psd-1.0.0/lib/psd.rb:14:in `each'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/psd-1.0.0/lib/psd.rb:14:in `<top (required)>'
/Users/sam/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
/Users/sam/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
/Users/sam/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
/Users/sam/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
/Users/sam/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
/Users/sam/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
/Users/sam/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
config.ru:3:in `block in inner_app'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `inner_app'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/shotgun-0.9/lib/shotgun/loader.rb:112:in `eval'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/shotgun-0.9/lib/shotgun/loader.rb:112:in `inner_app'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/shotgun-0.9/lib/shotgun/loader.rb:102:in `assemble_app'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/shotgun-0.9/lib/shotgun/loader.rb:86:in `proceed_as_child'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/shotgun-0.9/lib/shotgun/loader.rb:31:in `call!'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/shotgun-0.9/lib/shotgun/loader.rb:18:in `call'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/shotgun-0.9/lib/shotgun/favicon.rb:12:in `call'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/shotgun-0.9/lib/shotgun/static.rb:14:in `call'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/puma-2.5.1/lib/puma/server.rb:472:in `handle_request'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/puma-2.5.1/lib/puma/server.rb:343:in `process_client'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/puma-2.5.1/lib/puma/server.rb:242:in `block in run'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/puma-2.5.1/lib/puma/thread_pool.rb:92:in `call'
/Users/sam/Sites/psdfonts/vendor/bundle/ruby/2.0.0/gems/puma-2.5.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

**Comment by podarok** [comment]
```bundler upgrade``` helped me
